### ISSUE TITLE
[BUG] 404 after switching between forgot-password and login pages

### ISSUE THREAD

**Issue by Mikilll94** [refinedev/refine#4077]
### Describe the bug

![login bug](https://user-images.githubusercontent.com/17653648/229737668-38a6f850-9107-48f1-b8a4-e19f3084b551.gif)

After switching between `login` and `forgot-password`, we eventually got 404. Everything is shown on the movie.

### Steps To Reproduce

1. Run this repro project (it's a project from MUI + Supabase template with added `forgot-password` page)
[refine-test.zip](https://github.com/refinedev/refine/files/11146466/refine-test.zip)

2. Switch between `login` and `forgot-password` pages like shown on the GIF.
3. You will eventually get 404.

### Expected behavior

User should not be redirected to 404 page.

### Desktop

- macOS Big Sur 11.6.1
- Chrome 111.0.5563.146

**Comment by yildirayunlu** [comment]
Thank you for your feedback 🙏🏼 

Fixed this issue 🚀

**Comment by Mikilll94** [comment]
@yildirayunlu Where is the PR?

**Comment by yildirayunlu** [comment]
Hey @Mikilll94 `refine` projects use `superplate` as infrastructure. I fixed this issue in this [PR](https://github.com/pankod/superplate-core-plugins/pull/335).

**Comment by Mikilll94** [comment]
@yildirayunlu What package I need to update to have this fix?

**Comment by yildirayunlu** [comment]
@Mikilll94 You don't need to do any updates. Just start with `npx superplate-cli@latest`

**Comment by Mikilll94** [comment]
@yildirayunlu But this command is for creating a new project.

What I want is to fix this 404 bug in the existing project.

**Comment by Mikilll94** [comment]
@yildirayunlu @omeraplak 
BTW. I have discovered that this was not fixed properly. Now after clicking "Sign in" link on "Forgot password" page, the user is redirected to "Sign up"page. Just look at the GIF below:

![forgot_password_bug](https://user-images.githubusercontent.com/17653648/229928333-0b698c7c-fe44-4c46-bd3e-b753b6695b46.gif)

**Comment by omeraplak** [comment]
Hey @Mikilll94 ,
Thank you for reporting the issue. We've fixed it on [@refinedev/mui@4.5.10](https://github.com/refinedev/refine/releases/tag/%40refinedev%2Fmui%404.5.10) 🌟
